import alertCenter from '../components/sample/alertCenter.vue'
import alertSearch from '../components/sample/alertSearch.vue'
import code from '../components/sample/code.vue'
import alertRight from '../components/sample/alertRight.vue'
import lookimg from '../components/sample/lookimg.vue'
import alert from '../components/sample/alert.vue'
import slideTable from '../components/sample/slideTable.vue'
import index from '../components/sample/index.vue'
import picker from '../components/sample/picker.vue'
import accordion from '../components/sample/accordion.vue'
import actionsheet from '../components/sample/actionsheet.vue'
import badge from '../components/sample/badges.vue'
import buttons from '../components/sample/buttons.vue'
import numbutton from '../components/sample/buttons-with-badges.vue'
import iconbutton from '../components/sample/buttons-with-icons.vue'
import loadbutton from '../components/sample/buttons-with-loading.vue'
import card from '../components/sample/card.vue'
import checkboxs from '../components/sample/checkbox.vue'
import dialog from '../components/sample/dialog.vue'
import icons from '../components/sample/icons.vue'
import iconsLight from '../components/sample/icons-extra.vue'
import inputs from '../components/sample/input.vue'
import MediaList from '../components/sample/media-list.vue'
import numbox from '../components/sample/numbox.vue'
import slider from '../components/sample/slider-default.vue'
import sliderTable from '../components/sample/slider-table-default.vue'
import sliderTitle from '../components/sample/slider-with-title.vue'
import refresh from '../components/sample/refresh.vue'
import tabView from '../components/sample/tabView.vue'
import muiSample from '../components/sample/muiSample.vue'
import timeLine from '../components/sample/timeLine.vue'
import template from '../components/sample/template.vue'
import tableList from '../components/sample/tableList.vue'
import form from '../components/sample/form.vue'
import dateTable from '../components/sample/dateTable.vue'
import mode_table from '../components/sample/mode_table.vue'

export default{
	 alertCenter,
 alertSearch ,
 code ,
 alertRight ,
 lookimg ,
//import alert from '../components/sample/alert.vue'
//import slideTable from '../components/sample/slideTable.vue'
//import index from '../components/sample/index.vue'
//import picker from '../components/sample/picker.vue'
//import accordion from '../components/sample/accordion.vue'
//import actionsheet from '../components/sample/actionsheet.vue'
//import badge from '../components/sample/badges.vue'
//import buttons from '../components/sample/buttons.vue'
//import numbutton from '../components/sample/buttons-with-badges.vue'
//import iconbutton from '../components/sample/buttons-with-icons.vue'
//import loadbutton from '../components/sample/buttons-with-loading.vue'
//import card from '../components/sample/card.vue'
//import checkboxs from '../components/sample/checkbox.vue'
//import dialog from '../components/sample/dialog.vue'
//import icons from '../components/sample/icons.vue'
//import iconsLight from '../components/sample/icons-extra.vue'
//import inputs from '../components/sample/input.vue'
//import MediaList from '../components/sample/media-list.vue'
//import numbox from '../components/sample/numbox.vue'
//import slider from '../components/sample/slider-default.vue'
//import sliderTable from '../components/sample/slider-table-default.vue'
//import sliderTitle from '../components/sample/slider-with-title.vue'
//import refresh from '../components/sample/refresh.vue'
//import tabView from '../components/sample/tabView.vue'
//import muiSample from '../components/sample/muiSample.vue'
//import timeLine from '../components/sample/timeLine.vue'
//import template from '../components/sample/template.vue'
//import tableList from '../components/sample/tableList.vue'
//import form from '../components/sample/form.vue'
//import dateTable from '../components/sample/dateTable.vue'
//	mode_table,
}
